'use client';
import { use,useEffect,useRef,useState } from 'react';
import QRCode from 'qrcode';
type Payment={paymentId:string;flow:string;amountPaisa:number;status:string;scenario:string;serverTime:string;startedAt:string;expiresAt:string|null;windowExpired:boolean;qrPayload:string|null};
export default function PaymentPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [p,setP]=useState<Payment|null>(null);const [error,setError]=useState('');const [remaining,setRemaining]=useState(120);const [qr,setQr]=useState('');const [loading,setLoading]=useState(false);const clock=useRef({server:Date.now(),local:Date.now()});const latest=useRef<Payment|null>(null);const inflight=useRef(false);
 async function refresh(){if(inflight.current)return;inflight.current=true;setLoading(true);try{const r=await fetch('/api/payments/'+id,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to check payment.');latest.current=data;clock.current={server:Date.parse(data.serverTime),local:Date.now()};setP(data);setError('');}catch(e){setError((e as Error).message)}finally{inflight.current=false;setLoading(false)}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>{const current=latest.current;const now=clock.current.server+Date.now()-clock.current.local;const end=current?Date.parse(current.expiresAt||current.startedAt)+ (current.expiresAt?0:120000):now+120000;setRemaining(Math.max(0,Math.ceil((end-now)/1000)));if(current?.status==='PENDING'&&now<end&&!document.hidden)void refresh();},2000);function visible(){if(!document.hidden)void refresh()}document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible)};},[id]);
 useEffect(()=>{if(!p?.qrPayload){setQr('');return}let cancelled=false;QRCode.toDataURL(p.qrPayload,{width:280,margin:2,color:{dark:'#123936',light:'#ffffff'}}).then(v=>{if(!cancelled)setQr(v)});return()=>{cancelled=true}},[p?.qrPayload]);
 useEffect(()=>{const timer=setInterval(()=>{if(!latest.current)return;const current=latest.current;const now=clock.current.server+Date.now()-clock.current.local;const end=Date.parse(current.expiresAt||current.startedAt)+(current.expiresAt?0:120000);setRemaining(Math.max(0,Math.ceil((end-now)/1000)));},250);return()=>clearInterval(timer)},[]);
 const final=p&&['SUCCEEDED','FAILED'].includes(p.status);const success=p?.status==='SUCCEEDED';const expired=!final&&remaining===0;
 return <main className="payment-main"><a className="back" href="/">← Back to checkout</a><section className="payment-card"><div className="eyebrow">{p?.flow==='rtp'?'REQUEST TO PAY':'DYNAMIC QR'} · SIMULATION</div><h1>{!p?'Loading your payment…':final?success?'Payment complete':'Payment unsuccessful':expired?'Confirmation pending':p.flow==='qr'?'Your demo QR is ready':'Waiting for demo approval'}</h1><p className="muted">{final?'This is a simulated result. No money was moved.':p?.flow==='qr'?'This QR is for demonstration only. It cannot make a payment.':'Your fictional payer request is being simulated.'}</p>
 {p&&<div className="payment-amount"><span>PKR</span> {(p.amountPaisa/100).toFixed(2)}</div>}
 {final?<div className={'outcome '+(success?'success':'failed')}>{success?'✓':'×'}</div>:expired?<div className="expired-icon">◷</div>:p?.flow==='qr'?<div className="qr-wrap">{qr?<img src={qr} width={240} height={240} alt="Synthetic demo QR — not a payment instruction"/>:<div className="qr-placeholder">Preparing QR…</div>}<span>DEMO QR · NOT PAYABLE</span></div>:<div className="rtp-animation"><span>↗</span><p>Awaiting simulated response</p></div>}
 {!final&&p&&<div className="timer" role="status">{expired?(p.flow==='qr'?'Payment window expired—confirmation pending':'Still awaiting confirmation'):<> <span className="pulse"/> {p.flow==='qr'?'QR window':'Waiting window'} <b>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</b></>}</div>}
 <div className="payment-meta"><span>Demo reference</span><code>{p?.paymentId||'—'}</code><span>Scenario</span><b>{p?.scenario.replaceAll('-',' ')||'—'}</b></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {!final&&<button className="secondary" onClick={()=>void refresh()} disabled={loading}>{loading?'Checking…':'Refresh status'}</button>}<a className="primary" href="/">Start a new demo <span>→</span></a>{expired&&<p className="helper">A new attempt does not cancel this one. Late confirmations remain available through Refresh status.</p>}</section></main>;
}
