'use client';
import { useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { fixtures } from '@/lib/domain';
const choices=[{id:'success',label:'Successful payment',detail:'Confirms after 10 seconds',icon:'✓'},{id:'failure',label:'Failed payment',detail:'Declines after 10 seconds',icon:'×'},{id:'no-confirmation',label:'No confirmation',detail:'Explore the waiting experience',icon:'◷'},{id:'late-success',label:'Late confirmation',detail:'Confirms after 130 seconds',icon:'↻'}];
type Context={contextId:string;accountTitle:string;payerReference:string;amountPaisa:number};
export default function Checkout(){
 const router=useRouter(); const [flow,setFlow]=useState('qr');const [amount,setAmount]=useState('10.00');const [scenario,setScenario]=useState('success');const [payer,setPayer]=useState('demo-01');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [context,setContext]=useState<Context|null>(null);const key=useRef('');
 useEffect(()=>{fetch('/api/session').then(r=>{if(!r.ok)throw Error();setReady(true)}).catch(()=>setError('Unable to start a demo session. Please reload.'));},[]);
 function change(action:()=>void){action();setContext(null);setError('');key.current='';}
 async function submit(event:React.FormEvent){event.preventDefault();if(busy||!ready)return;setBusy(true);setError('');key.current ||= crypto.randomUUID();
  try{const operation=flow==='qr'?'qr':context?'rtp':'title-fetch';const r=await fetch('/api/payments/'+operation,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify(context?{contextId:context.contextId}:{amountPkr:amount,scenario,payerId:payer})});const data=await r.json();if(!r.ok)throw Error(data.error||'Request unavailable.');key.current='';if(operation==='title-fetch')setContext(data);else router.push('/payments/'+data.paymentId);}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 return <main className="checkout"><section className="intro"><div className="eyebrow">PAYMENTS, MADE SIMPLE</div><h1>A faster way<br/> to <em>pay.</em></h1><p className="lead">Experience RAAST at checkout.<br/>Scan a QR or try Request to Pay—all in a simulation.</p><div className="features"><div><span>01</span><div><b>Choose your payment</b><p>Two familiar journeys, one simple checkout.</p></div></div><div><span>02</span><div><b>Explore the outcome</b><p>Try success, failure, or a delayed confirmation.</p></div></div><div><span>03</span><div><b>See every step</b><p>Follow the payment status as it changes.</p></div></div></div><div className="sandbox-note"><span>◇</span><p><b>Built for exploration</b><br/>No bank app, real account, or funds needed.</p></div></section>
 <section className="checkout-card"><div className="card-heading"><div><span className="eyebrow">DEMO CHECKOUT</span><h2>Let’s make a payment</h2></div><div className="raast-logo">راست<span>RAAST</span></div></div><form onSubmit={submit}>
 <label className="label" htmlFor="amount">Payment amount</label><div className="amount-input"><span>PKR</span><input id="amount" inputMode="decimal" value={amount} onChange={e=>change(()=>setAmount(e.target.value))} required aria-describedby="amount-help" disabled={busy}/></div><p className="helper" id="amount-help">Choose any amount from PKR 1 to PKR 100.</p>
 <fieldset disabled={busy}><legend>How would you like to pay?</legend><div className="flow-options">{['qr','rtp'].map(f=><button key={f} type="button" className={'flow '+(flow===f?'selected':'')} aria-pressed={flow===f} onClick={()=>change(()=>setFlow(f))}><span className="flow-icon">{f==='qr'?'▦':'↗'}</span><span><b>{f==='qr'?'Dynamic QR':'Request to Pay'}</b><small>{f==='qr'?'Generate a demo QR':'Confirm a demo payer'}</small></span><span className="radio"/></button>)}</div></fieldset>
 {flow==='rtp'&&<div className="payer"><label className="label" htmlFor="payer">Fictional payer</label><select id="payer" disabled={busy} value={payer} onChange={e=>change(()=>setPayer(e.target.value))}>{fixtures.map(f=><option value={f.id} key={f.id}>{f.title} · {f.bank}</option>)}</select><p className="helper">Demo identities only. Do not enter personal bank details.</p></div>}
 <label className="label" htmlFor="scenario">Simulation scenario</label><select id="scenario" value={scenario} disabled={busy} onChange={e=>change(()=>setScenario(e.target.value))}>{choices.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><p className="helper">{choices.find(c=>c.id===scenario)?.detail}. This selection controls the demo result.</p>
 {context&&<div className="confirmation"><span className="eyebrow">CONFIRM YOUR DEMO PAYER</span><b>{context.accountTitle}</b><span>{context.payerReference} · PKR {(context.amountPaisa/100).toFixed(2)}</span><p>No real account lookup was performed.</p></div>}
 {error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!ready||busy} type="submit">{busy?'Preparing your demo…':flow==='qr'?'Generate demo QR':context?'Confirm & request payment':'Fetch demo account title'}<span>→</span></button><p className="disclaimer">This is a simulation. No real payment will be initiated.</p></form></section></main>;
}
